---
- name: Open http port 80
  community.general.ufw:
    rule: allow
    port: "{{ http_port | default('80') }}"
    proto: tcp
    comment: http
    state: enabled

- name: Open https port 443
  community.general.ufw:
    rule: allow
    port: "{{ https_port | default('443') }}"
    proto: tcp
    comment: https

- name: Ensure apache2 is stopped and disabled
  ansible.builtin.service:
    name: apache2
    enabled: false
    state: stopped
  register: unused_disable
  failed_when: unused_disable is failed and ('find' not in unused_disable.msg and 'found' not in unused_disable.msg) # this prevents failing when the service is not found

- name: Updating and Upgrading
  ansible.builtin.apt:
    upgrade: "yes"
    update_cache: true
    cache_valid_time: 3600

- name: Installing Nginx
  ansible.builtin.apt:
    name:
      - nginx
      - libwww-perl # required for munin monitoring
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: Disabling nginx version show
  ansible.builtin.lineinfile:
    dest: /etc/nginx/nginx.conf
    regex: .*server_tokens off
    line: "\tserver_tokens off;"
    insertafter: types_hash_max_size
  notify: Reload Nginx

- name: Remove default nginx site
  ansible.builtin.file:
    name: /etc/nginx/sites-enabled/default
    state: absent

- name: Generating Diffie–Hellman key parameters, takes a while, you may grab some coffee
  ansible.builtin.command: openssl dhparam -out /etc/nginx/dhparams.pem 2048
  args:
    creates: /etc/nginx/dhparams.pem
  notify: Reload Nginx

- name: Creating nginx upstream directory
  ansible.builtin.file:
    path: /etc/nginx/conf.d/upstream
    state: directory
    owner: root
    group: root
    mode: "0755"
  register: upstream_directory

- name: Location configs munin
  ansible.builtin.template:
    src: nginx/{{ server_monitoring | trim }}.j2
    dest: /etc/nginx/conf.d/upstream/munin.conf
    owner: root
    group: root
    mode: "0644"
  notify: Reload Nginx
  when:
    - groups['monitoring'] | length > 0
    - server_monitoring is defined

- name: Include tasks securing-munin
  ansible.builtin.include_tasks: securing-{{ server_monitoring | trim }}.yml
  when:
    - groups['monitoring'] | length > 0
    - server_monitoring is defined
