---
# defaults file for roles/integration
jar_file_path: "/opt/civil_registry.jar"
service_name: "civil_registry"
service_user: "civil_registry"
service_group: "civil_registry"
java_opts: "-Xms512m -Xmx1024m"
working_directory: "/usr/local/bin/civil_registry/"
service_port: 8080 
allowed_ips:
  - "172.19.1.11"   # DHIS2 Server
  # - "172.19.1.11"    # Reverse Proxy
